version: "3.6"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: on-failure
    networks:
      - net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: on-failure
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  rstudio:
    image: rocker/tidyverse:3.6.0
    container_name: rstudio
    restart: on-failure
    volumes:
      - type: volume
        source: rstudio
        target: /home/rstudio
        volume:
          no-copy: true
      - type: bind
        source: ./projects
        target: /home/rstudio/projects
      - type: volume
        source: r_libs
        target: /usr/local/lib/R
        volume:
          no-copy: true
    networks:
      - net
    environment:
      - PASSWORD=rstudio1
    expose:
      - 8787

networks:
  tki-net:
    name: net

volumes:
  r_libs:
  rstudio:
